# Generated by Django 5.0.4 on 2024-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceandEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Education', 'Education'), ('Experience', 'Experience')], max_length=40)),
                ('in_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceandEducationResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('exprence', models.ManyToManyField(to='post.experienceandeducation')),
            ],
        ),
    ]
