# Generated by Django 5.0.4 on 2024-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_experienceandeducation_experienceandeducationresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceandeducationresume',
            name='type',
            field=models.CharField(choices=[('Education', 'Education'), ('Experience', 'Experience')], max_length=40),
        ),
    ]
