# Generated by Django 5.0.4 on 2024-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_experienceandeducationresume_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Personal', 'Personal'), ('Professional', 'Professional')], max_length=40)),
                ('title', models.CharField(max_length=30)),
                ('parsentage', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='experienceandeducationresume',
            name='type',
            field=models.CharField(choices=[('EDUCATION', 'EDUCATION'), ('EXPRTIENCE', 'EXPRTIENCE')], max_length=40),
        ),
        migrations.CreateModel(
            name='SkillResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('skill', models.ManyToManyField(to='post.skill')),
            ],
        ),
    ]
